[package]
name = "snake"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
macroquad = "0.3.25"
[target.x86_64-unknown-linux-gnu]
rustflags = ["-C", "linker-flavor=ld.lld"]